apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  VAULT_ADDR: 'http://vault.vault.svc.cluster.local:8200'
  AVP_K8S_ROLE: vplugin
  AVP_TYPE: vault
  AVP_AUTH_TYPE: k8s