kind: Secret
apiVersion: v1
metadata:
  namespace: vplugin-demo
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/vplugin/supersecret"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
stringData:
  username: <username>
  password: <password>